# Minecraft server properties
# Safe starter config for a small Paper server.
server-port=25565
motd=Paper server gratuit - GitHub + Oracle
online-mode=true
white-list=true
enforce-whitelist=true
max-players=10
difficulty=normal
gamemode=survival
pvp=true
spawn-protection=16
view-distance=8
simulation-distance=6
enable-command-block=false
enable-rcon=false
enable-query=false
allow-flight=false
allow-nether=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
generate-structures=true
level-name=world
level-seed=
resource-pack=
resource-pack-sha1=
